# Rex OS - Limine bootloader configuration
# Limine v9.x boot protocol

timeout: 0
default_entry: 1

/Rex OS
    protocol: limine
    path: boot():/boot/rexos.elf
    module_path: boot():/boot/initrd.tar
